### ISSUE TITLE
Enable combining integrations from multiple FITS files

### ISSUE THREAD

**Issue by vandalt** [SAIL-Labs/AMICAL#153]
For cases where the observations are split in multiple FITS files with the exact same setup, it would be nice to have a straightforward way to combine the observations. A good data set to test this would be the JWST ERS AMI observations. Here are the potential options I have in mind:

- Don't change anything in AMICAL and let users create their own combined FITS cubes before using AMICAL.
- Make cleaning and extraction functions accept a cube and a header instead of a filename.
- Make cleaning and extraction functions accept a list of filenames instead of a single one.
- Don't change anything in the extraction and combine interferometric observable before searching for companions.

The advantage of the last one is that it enables correcting for potential PA difference between the cubes. For example the ERS data has a 2e-6 deg (~ 7 mas) `ROLL_REF` difference between consecutive cubes. The commissioning PA results gave ~ 0.05 deg precision on the fitted PA for AB Dor, so it would be negligible in this case, but maybe it could be a problem with future datasets?

@DrSoulain  @benjaminpope @neutrinoceros what is your opinion on this?

**Comment by neutrinoceros** [comment]
I'm all for supporting common workflows natively, but I think accepting cubes or list of filenames are potentially bad because
1) it's not obvious what would be the expected outputs (a combined output, or just the equivalent of running a loop ?)
2) we'd open the door on adding much more type flexibility than we can chew in the future

Would it make sense to instead have an interface dedicated to combining inputs (or outputs ?) so that the rest of the library could then be reused as is ?

(Don't mind me if anything I said here doesn't make sense in the context, I'm still very much of a layman in terms of what AMICAL does or is used for, my expertise is supposedly with the maintenance and design aspects)

**Comment by DrSoulain** [comment]
it depends what you want to do exactly. (1) If you want to increase your statistic to compute your observable, yes you want to combine the cube. (2) if you want to fit more data to compute a detection, you can compute different oifits file and then use all of them to fit your best model. 

Then, if you combine different cube, you have to take into account the PA variation. Maybe even within the cube if you have long integration sequence for instance.
